package model;
// Generated 26.Eyl.2019 23:23:24 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "foodtown")
public class Category implements java.io.Serializable {

	private int ctid;
	private String ctname;

	public Category() {
	}

	public Category(int ctid, String ctname) {
		this.ctid = ctid;
		this.ctname = ctname;
	}

	@Id

	@Column(name = "ctid", unique = true, nullable = false)
	public int getCtid() {
		return this.ctid;
	}

	public void setCtid(int ctid) {
		this.ctid = ctid;
	}

	@Column(name = "ctname", nullable = false, length = 32)
	public String getCtname() {
		return this.ctname;
	}

	public void setCtname(String ctname) {
		this.ctname = ctname;
	}

}
