package model;
// Generated 26.Eyl.2019 23:23:24 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "foodtown")
public class Customer implements java.io.Serializable {

	private int cid;
	private String cname;
	private String cmail;
	private String cpass;
	private String caddress;

	public Customer() {
	}

	public Customer(int cid, String cname, String cmail, String cpass, String caddress) {
		this.cid = cid;
		this.cname = cname;
		this.cmail = cmail;
		this.cpass = cpass;
		this.caddress = caddress;
	}

	@Id

	@Column(name = "cid", unique = true, nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "cname", nullable = false)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "cmail", nullable = false)
	public String getCmail() {
		return this.cmail;
	}

	public void setCmail(String cmail) {
		this.cmail = cmail;
	}

	@Column(name = "cpass", nullable = false, length = 32)
	public String getCpass() {
		return this.cpass;
	}

	public void setCpass(String cpass) {
		this.cpass = cpass;
	}

	@Column(name = "caddress", nullable = false)
	public String getCaddress() {
		return this.caddress;
	}

	public void setCaddress(String caddress) {
		this.caddress = caddress;
	}

}
