package model;
// Generated 26.Eyl.2019 23:23:24 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "foodtown")
public class Product implements java.io.Serializable {

	private int pid;
	private String ptitle;
	private String pdesc;
	private String pphoto;
	private BigDecimal pprice;
	private int ctid;

	public Product() {
	}

	public Product(int pid, String ptitle, String pdesc, String pphoto, BigDecimal pprice, int ctid) {
		this.pid = pid;
		this.ptitle = ptitle;
		this.pdesc = pdesc;
		this.pphoto = pphoto;
		this.pprice = pprice;
		this.ctid = ctid;
	}

	@Id

	@Column(name = "pid", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "ptitle", nullable = false)
	public String getPtitle() {
		return this.ptitle;
	}

	public void setPtitle(String ptitle) {
		this.ptitle = ptitle;
	}

	@Column(name = "pdesc", nullable = false)
	public String getPdesc() {
		return this.pdesc;
	}

	public void setPdesc(String pdesc) {
		this.pdesc = pdesc;
	}

	@Column(name = "pphoto", nullable = false, length = 500)
	public String getPphoto() {
		return this.pphoto;
	}

	public void setPphoto(String pphoto) {
		this.pphoto = pphoto;
	}

	@Column(name = "pprice", nullable = false, precision = 10)
	public BigDecimal getPprice() {
		return this.pprice;
	}

	public void setPprice(BigDecimal pprice) {
		this.pprice = pprice;
	}

	@Column(name = "ctid", nullable = false)
	public int getCtid() {
		return this.ctid;
	}

	public void setCtid(int ctid) {
		this.ctid = ctid;
	}

}
